modLoader="javafml"
loaderVersion="[47,)"
license="GPL License"

[[mods]]
modId="blue_oceans"
version="1.1.4a-pre9"
displayName="Blue Oceans"
displayURL="https://github.com/NineAbyss9"
logoFile="logo.png"
credits="NineAbyss9"
authors="NineAbyss9"
description="A fun mod!"

[[dependencies.blue_oceans]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"