modLoader="javafml"
loaderVersion="[47,)"
license="GPLv2"

[[mods]]
modId="blue_oceans"
version="1.1.4b-release2"
displayName="Blue Oceans"
displayURL="https://github.com/NineAbyss9"
logoFile="logo.png"
credits="NineAbyss9"
authors="NineAbyss9"
description="A fun mod!"

[[dependencies.blue_oceans]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.blue_oceans]]
modId = "ix_api"
mandatory = true
versionRange = "[1.,)"
ordering = "AFTER"
side = "BOTH"