@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bilibili.player_ix.blue_oceans.common.entities.red_plum.red_plum_girl;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;